name: Build GDAL Wheel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        gdal-version: [3.10.2]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Add GDAL 3.10.2 PPA
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
          sudo apt-get update

      - name: Install GDAL 3.10.2 and dependencies
        run: |
          sudo apt-get install -y \
            gdal-bin=3.10.2+dfsg-1~* \
            libgdal-dev=3.10.2+dfsg-1~* \
            python3-dev \
            build-essential

      - name: Set environment paths for GDAL headers
        run: |
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV

      - name: Install pip dependencies and build GDAL wheel
        run: |
          pip install --upgrade pip setuptools wheel
          pip install GDAL==3.10.2
          pip wheel GDAL==3.10.2 --wheel-dir dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: gdal-wheel-${{ matrix.python-version }}
          path: dist/*.whl