name: Build GDAL Wheel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        gdal-version: [3.10.2]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pip, setuptools, wheel
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel numpy

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-dev \
            python3-pip \
            wget \
            cmake \
            ninja-build \
            curl \
            git \
            unzip \
            libtiff-dev \
            libjpeg-dev \
            libgif-dev \
            libsqlite3-dev \
            libpq-dev \
            libcurl4-openssl-dev \
            libgeos-dev \
            libspatialite-dev \
            libproj-dev \
            libopenjp2-7-dev \
            libwebp-dev \
            libxml2-dev \
            libexpat1-dev \
            libxerces-c-dev \
            libpoppler-dev \
            libpoppler-private-dev \
            libfreexl-dev \
            libhdf5-serial-dev \
            libnetcdf-dev \
            liblzma-dev \
            libzstd-dev

      - name: Download and build GDAL from source with CMake
        run: |
          wget https://github.com/OSGeo/gdal/releases/download/v3.10.2/gdal-3.10.2.tar.gz
          tar -xzf gdal-3.10.2.tar.gz
          mkdir -p gdal-3.10.2/build
          cd gdal-3.10.2/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build GDAL Python wheel
        run: |
          GDAL_VERSION=3.10.2 pip wheel GDAL==3.10.2 --wheel-dir dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: gdal-wheel-${{ matrix.python-version }}
          path: dist/*.whl