name: Build GDAL Wheel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        gdal-version: [3.6.0]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            gdal-bin \
            python3-dev \
            python3-pip

      - name: Set GDAL version and install wheel
        run: |
          pip install --upgrade pip setuptools wheel
          pip install numpy
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          GDAL_VERSION=${{ matrix.gdal-version }}
          pip install GDAL==${GDAL_VERSION} --global-option=build_ext --global-option="-I/usr/include/gdal"

      - name: Build GDAL wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: gdal-wheel-${{ matrix.python-version }}
          path: dist/*.whl