name: Build GDAL Wheel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        gdal-version: [3.8.4]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build GDAL wheel using make
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/manylinux_2_28_x86_64
          options: --user root --volume ${{ github.workspace }}:/io
          run: |
            cd /io
            make wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: gdal-wheel-${{ matrix.python-version }}
          path: dist/*.whl