name: Build GDAL Wheel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        gdal-version: [3.8.4]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build wheels using Docker
        run: |
          make wheels

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: gdal-wheel-${{ matrix.python-version }}
          path: dist/*.whl